### ISSUE TITLE
is eStore image are float or int format

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_raytrace#17]
Hello.
My question is about final image. 
Is used float or integer format for image data?

**Comment by mklefrancois** [comment]
Hi @tigrazone , the output image has the following format
```
VkFormat m_offscreenColorFormat{VK_FORMAT_R32G32B32A32_SFLOAT};
```

You can find the creation of the image under `RenderOutput::createOffscreenRender()`. We are using float because of the accumulation of the frame. When displaying the rendered image, we run a fragment shader with this image as input and the swap-image attached to the frame-buffer.

**Comment by tigrazone** [comment]
Thanks a lot!
