### ISSUE TITLE
black edges occur when zoom in

### ISSUE THREAD

**Issue by f1shel** [nvpro-samples/vk_raytrace#18]
Hi, thanks for this greate project!

I encountered a problem which seems like a bug.

Take the `robot-toon` scene for example, when you zoom in to observe the model, some black lines will occur around the contour, as shown in the figure below.

![1](https://user-images.githubusercontent.com/83902932/169484049-dda6f763-b0a4-4ded-964a-cdfcfa2ba6b2.png)
![2](https://user-images.githubusercontent.com/83902932/169484059-0b0c8d0e-252f-474c-b540-2c4d8310e349.png)

This will also happen to other contours. Is that a bug?

**Comment by f1shel** [comment]
another example
![3](https://user-images.githubusercontent.com/83902932/169489299-6d189797-86cb-4b9f-8d7b-ba6c403a930b.png)

**Comment by droettger** [comment]
That is a usual artifact when rendering low-poly models with interpolated per-vertex shading normals.

At high geometry curvatures, which appear along the silhouettes of this object, it can happen that the interpolated shading normal across a triangle primitive actually doesn't lie inside the same hemisphere as the direction to the viewer (negative ray direction) and that's a false condition for the lighting test. For the shading calculation that's like looking at the backface of an opaque object. (This would not happen when using the face-normals instead of the shading normals, but then you get a facetted look.)

Similar effects would arise when the sampled continuation ray in a path tracer would continue below the geometric surface of opaque materials, which also happens regularly with bump- or normal-maps.

This site has some nice images explaining interpolated shading normals:
https://www.scratchapixel.com/lessons/3d-basic-rendering/introduction-to-shading/shading-normals

The black areas are running into the dot(V, N) < 0.0 case.

**Comment by Kuranes** [comment]
@[f1shel](https://github.com/f1shel) FYI 
it's know topic with possible mitigation stragegies
as per the publication "Consistent Normal Interpolation", Reshetov et al., 2010
 https://blog.yiningkarlli.com/2015/01/consistent-normal-interpolation.html
 and an [implementation here](https://twitter.com/j_bikker/status/1107938914868908032)
- https://github.com/jbikker/lighthouse2/blob/dcc64b4a401b7d0db4b3e75c1f3dbcfd8adb3102/lib/rendercore_vulkan_rt/shaders/tools.glsl#L259-L279
- https://github.com/jbikker/lighthouse2/blob/dcc64b4a401b7d0db4b3e75c1f3dbcfd8adb3102/lib/rendercore_vulkan_rt/shaders/tools.glsl#L259-L279
